// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Talad.Infrastructure.Persistence;

#nullable disable

namespace Talad.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TaladDbContext))]
    [Migration("20260923143854_AddCartMember")]
    partial class AddCartMember
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Talad.Domain.Accounts.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("Talad.Domain.Catalog.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentPriceVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("current_price_version_id");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("low_stock_threshold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("StockQty")
                        .HasColumnType("integer")
                        .HasColumnName("stock_qty");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasFilter("barcode IS NOT NULL AND status = 'Active'");

                    b.HasIndex("CurrentPriceVersionId");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_low_stock_threshold", "low_stock_threshold >= 0");

                            t.HasCheckConstraint("ck_products_stock_qty", "stock_qty >= 0");
                        });
                });

            modelBuilder.Entity("Talad.Domain.Catalog.ProductPriceVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int>("ChangedById")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_id");

                    b.Property<decimal?>("PreviousPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("previous_price");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("ProductId");

                    b.ToTable("product_price_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_price_versions_price", "price > 0");
                        });
                });

            modelBuilder.Entity("Talad.Domain.Members.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccumulatedAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("accumulated_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("HiddenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hidden_at");

                    b.Property<int?>("HiddenById")
                        .HasColumnType("integer")
                        .HasColumnName("hidden_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("HiddenById");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_members_phone_active")
                        .HasFilter("status = 'Active'");

                    b.ToTable("members", null, t =>
                        {
                            t.HasCheckConstraint("ck_members_accumulated_amount", "accumulated_amount >= 0");
                        });
                });

            modelBuilder.Entity("Talad.Domain.Sales.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasFilter("status = 'Open'");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("Talad.Domain.Sales.CartLine", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("integer")
                        .HasColumnName("cart_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.HasKey("CartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("cart_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_cart_lines_qty", "qty >= 1");
                        });
                });

            modelBuilder.Entity("Talad.Domain.Catalog.Product", b =>
                {
                    b.HasOne("Talad.Domain.Catalog.ProductPriceVersion", "CurrentPriceVersion")
                        .WithMany()
                        .HasForeignKey("CurrentPriceVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentPriceVersion");
                });

            modelBuilder.Entity("Talad.Domain.Catalog.ProductPriceVersion", b =>
                {
                    b.HasOne("Talad.Domain.Accounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talad.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Talad.Domain.Members.Member", b =>
                {
                    b.HasOne("Talad.Domain.Accounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talad.Domain.Accounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("HiddenById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Talad.Domain.Sales.Cart", b =>
                {
                    b.HasOne("Talad.Domain.Members.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Talad.Domain.Accounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Talad.Domain.Sales.CartLine", b =>
                {
                    b.HasOne("Talad.Domain.Sales.Cart", null)
                        .WithMany("Lines")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talad.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Talad.Domain.Sales.Cart", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
