// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Talad.Infrastructure.Persistence;

#nullable disable

namespace Talad.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TaladDbContext))]
    [Migration("20260924004603_AddSales")]
    partial class AddSales
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Talad.Domain.Accounts.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("Talad.Domain.Catalog.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentPriceVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("current_price_version_id");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text")
                        .HasColumnName("image_path");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("low_stock_threshold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("StockQty")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("stock_qty");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasFilter("barcode IS NOT NULL AND status = 'Active'");

                    b.HasIndex("CurrentPriceVersionId");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("ck_products_low_stock_threshold", "low_stock_threshold >= 0");

                            t.HasCheckConstraint("ck_products_stock_qty", "stock_qty >= 0");
                        });
                });

            modelBuilder.Entity("Talad.Domain.Catalog.ProductPriceVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int>("ChangedById")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_id");

                    b.Property<decimal?>("PreviousPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("previous_price");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("ProductId");

                    b.ToTable("product_price_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_product_price_versions_price", "price > 0");
                        });
                });

            modelBuilder.Entity("Talad.Domain.Catalog.StockAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AdjustedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("adjusted_at");

                    b.Property<int>("AdjustedById")
                        .HasColumnType("integer")
                        .HasColumnName("adjusted_by_id");

                    b.Property<int?>("CountedQty")
                        .HasColumnType("integer")
                        .HasColumnName("counted_qty");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_delta");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("RequestKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_key");

                    b.HasKey("Id");

                    b.HasIndex("AdjustedById");

                    b.HasIndex("RequestKey")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_adjustments_request_key");

                    b.HasIndex("ProductId", "AdjustedAt", "Id")
                        .HasDatabaseName("ix_stock_adjustments_product_adjusted_at");

                    b.ToTable("stock_adjustments", null, t =>
                        {
                            t.HasCheckConstraint("ck_stock_adjustments_counted_qty", "counted_qty IS NULL OR counted_qty >= 0");

                            t.HasCheckConstraint("ck_stock_adjustments_quantity_delta", "quantity_delta <> 0");
                        });
                });

            modelBuilder.Entity("Talad.Domain.Members.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AccumulatedAmount")
                        .IsConcurrencyToken()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("accumulated_amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateTimeOffset?>("HiddenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("hidden_at");

                    b.Property<int?>("HiddenById")
                        .HasColumnType("integer")
                        .HasColumnName("hidden_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("HiddenById");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("ix_members_phone_active")
                        .HasFilter("status = 'Active'");

                    b.ToTable("members", null, t =>
                        {
                            t.HasCheckConstraint("ck_members_accumulated_amount", "accumulated_amount >= 0");
                        });
                });

            modelBuilder.Entity("Talad.Domain.Promotions.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("CurrentVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("current_version_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("Status");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("Talad.Domain.Promotions.PromotionVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("created_by_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<int?>("FreeProductId")
                        .HasColumnType("integer")
                        .HasColumnName("free_product_id");

                    b.Property<int?>("FreeQty")
                        .HasColumnType("integer")
                        .HasColumnName("free_qty");

                    b.Property<decimal?>("MinSubtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("min_subtotal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ProductAId")
                        .HasColumnType("integer")
                        .HasColumnName("product_a_id");

                    b.Property<int?>("ProductBId")
                        .HasColumnType("integer")
                        .HasColumnName("product_b_id");

                    b.Property<int>("PromotionId")
                        .HasColumnType("integer")
                        .HasColumnName("promotion_id");

                    b.Property<int?>("QtyA")
                        .HasColumnType("integer")
                        .HasColumnName("qty_a");

                    b.Property<int?>("QtyB")
                        .HasColumnType("integer")
                        .HasColumnName("qty_b");

                    b.Property<int?>("RatePercent")
                        .HasColumnType("integer")
                        .HasColumnName("rate_percent");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FreeProductId");

                    b.HasIndex("ProductAId");

                    b.HasIndex("ProductBId");

                    b.HasIndex("PromotionId");

                    b.ToTable("promotion_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_promotion_versions_dates", "end_date IS NULL OR end_date >= start_date");

                            t.HasCheckConstraint("ck_promotion_versions_free_qty", "free_qty IS NULL OR free_qty >= 1");

                            t.HasCheckConstraint("ck_promotion_versions_min_subtotal", "min_subtotal IS NULL OR min_subtotal >= 0");

                            t.HasCheckConstraint("ck_promotion_versions_qty_a", "qty_a IS NULL OR qty_a >= 1");

                            t.HasCheckConstraint("ck_promotion_versions_qty_b", "qty_b IS NULL OR qty_b >= 1");

                            t.HasCheckConstraint("ck_promotion_versions_rate", "rate_percent IS NULL OR rate_percent BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Talad.Domain.Sales.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasFilter("status = 'Open'");

                    b.ToTable("carts", (string)null);
                });

            modelBuilder.Entity("Talad.Domain.Sales.CartLine", b =>
                {
                    b.Property<int>("CartId")
                        .HasColumnType("integer")
                        .HasColumnName("cart_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.HasKey("CartId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("cart_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_cart_lines_qty", "qty >= 1");
                        });
                });

            modelBuilder.Entity("Talad.Domain.Sales.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BillDiscount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("bill_discount");

                    b.Property<int?>("BillPromotionVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("bill_promotion_version_id");

                    b.Property<int>("CartId")
                        .HasColumnType("integer")
                        .HasColumnName("cart_id");

                    b.Property<decimal>("MemberDiscount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("member_discount");

                    b.Property<int?>("MemberDiscountVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("member_discount_version_id");

                    b.Property<int?>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<decimal>("NetTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("net_total");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<decimal>("PromoDiscountTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("promo_discount_total");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("receipt_no");

                    b.Property<int>("SellerId")
                        .HasColumnType("integer")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("subtotal");

                    b.Property<string>("VoidReason")
                        .HasColumnType("text")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<int?>("VoidedById")
                        .HasColumnType("integer")
                        .HasColumnName("voided_by_id");

                    b.HasKey("Id");

                    b.HasIndex("BillPromotionVersionId");

                    b.HasIndex("CartId")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_cart_id");

                    b.HasIndex("MemberDiscountVersionId");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_sales_member_id");

                    b.HasIndex("ReceiptNo")
                        .IsUnique()
                        .HasDatabaseName("ix_sales_receipt_no");

                    b.HasIndex("VoidedById");

                    b.HasIndex("PaidAt", "Id")
                        .HasDatabaseName("ix_sales_paid_at");

                    b.HasIndex("SellerId", "PaidAt")
                        .HasDatabaseName("ix_sales_seller_paid_at");

                    b.HasIndex("Status", "PaidAt")
                        .HasDatabaseName("ix_sales_status_paid_at");

                    b.ToTable("sales", null, t =>
                        {
                            t.HasCheckConstraint("ck_sales_amounts", "subtotal >= 0 AND promo_discount_total >= 0 AND bill_discount >= 0 AND member_discount >= 0 AND net_total >= 0");

                            t.HasCheckConstraint("ck_sales_void", "status <> 'Voided' OR (voided_by_id IS NOT NULL AND voided_at IS NOT NULL AND length(trim(void_reason)) > 0)");
                        });
                });

            modelBuilder.Entity("Talad.Domain.Sales.SaleLine", b =>
                {
                    b.Property<int>("SaleId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_id");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<int>("FreeQty")
                        .HasColumnType("integer")
                        .HasColumnName("free_qty");

                    b.Property<decimal>("LineNet")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("line_net");

                    b.Property<int>("PriceVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("price_version_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal>("PromoDiscount")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("promo_discount");

                    b.Property<int?>("PromotionVersionId")
                        .HasColumnType("integer")
                        .HasColumnName("promotion_version_id");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("SaleId", "LineNo");

                    b.HasIndex("PriceVersionId");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_sale_lines_product_id");

                    b.HasIndex("PromotionVersionId");

                    b.ToTable("sale_lines", null, t =>
                        {
                            t.HasCheckConstraint("ck_sale_lines_amounts", "unit_price >= 0 AND promo_discount >= 0 AND line_net >= 0");

                            t.HasCheckConstraint("ck_sale_lines_qty", "qty >= 1 AND free_qty >= 0 AND free_qty <= qty");
                        });
                });

            modelBuilder.Entity("Talad.Domain.Settings.MemberDiscountVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<int>("ChangedById")
                        .HasColumnType("integer")
                        .HasColumnName("changed_by_id");

                    b.Property<int>("RatePercent")
                        .HasColumnType("integer")
                        .HasColumnName("rate_percent");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.ToTable("member_discount_versions", null, t =>
                        {
                            t.HasCheckConstraint("ck_member_discount_versions_rate", "rate_percent BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Talad.Domain.Catalog.Product", b =>
                {
                    b.HasOne("Talad.Domain.Catalog.ProductPriceVersion", "CurrentPriceVersion")
                        .WithMany()
                        .HasForeignKey("CurrentPriceVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentPriceVersion");
                });

            modelBuilder.Entity("Talad.Domain.Catalog.ProductPriceVersion", b =>
                {
                    b.HasOne("Talad.Domain.Accounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talad.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Talad.Domain.Catalog.StockAdjustment", b =>
                {
                    b.HasOne("Talad.Domain.Accounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("AdjustedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talad.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Talad.Domain.Members.Member", b =>
                {
                    b.HasOne("Talad.Domain.Accounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talad.Domain.Accounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("HiddenById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Talad.Domain.Promotions.Promotion", b =>
                {
                    b.HasOne("Talad.Domain.Promotions.PromotionVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("Talad.Domain.Promotions.PromotionVersion", b =>
                {
                    b.HasOne("Talad.Domain.Accounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talad.Domain.Catalog.Product", "FreeProduct")
                        .WithMany()
                        .HasForeignKey("FreeProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Talad.Domain.Catalog.Product", "ProductA")
                        .WithMany()
                        .HasForeignKey("ProductAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Talad.Domain.Catalog.Product", "ProductB")
                        .WithMany()
                        .HasForeignKey("ProductBId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Talad.Domain.Promotions.Promotion", null)
                        .WithMany()
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FreeProduct");

                    b.Navigation("ProductA");

                    b.Navigation("ProductB");
                });

            modelBuilder.Entity("Talad.Domain.Sales.Cart", b =>
                {
                    b.HasOne("Talad.Domain.Members.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Talad.Domain.Accounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Talad.Domain.Sales.CartLine", b =>
                {
                    b.HasOne("Talad.Domain.Sales.Cart", null)
                        .WithMany("Lines")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Talad.Domain.Catalog.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Talad.Domain.Sales.Sale", b =>
                {
                    b.HasOne("Talad.Domain.Promotions.PromotionVersion", null)
                        .WithMany()
                        .HasForeignKey("BillPromotionVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Talad.Domain.Sales.Cart", null)
                        .WithMany()
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talad.Domain.Settings.MemberDiscountVersion", null)
                        .WithMany()
                        .HasForeignKey("MemberDiscountVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Talad.Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Talad.Domain.Accounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talad.Domain.Accounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("VoidedById")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Talad.Domain.Sales.SaleLine", b =>
                {
                    b.HasOne("Talad.Domain.Catalog.ProductPriceVersion", null)
                        .WithMany()
                        .HasForeignKey("PriceVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talad.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Talad.Domain.Promotions.PromotionVersion", null)
                        .WithMany()
                        .HasForeignKey("PromotionVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Talad.Domain.Sales.Sale", null)
                        .WithMany("Lines")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Talad.Domain.Settings.MemberDiscountVersion", b =>
                {
                    b.HasOne("Talad.Domain.Accounts.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Talad.Domain.Sales.Cart", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Talad.Domain.Sales.Sale", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
